

import type { Metadata } from "next";
import "./globals.css";
import { PokemonProvider } from "./context/pokemonContext";
import Logo from "./components/Logo";
import Link from "next/link";
import Styles from "./styles/layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Link href={"/"}>
          <Logo />
        </Link>
        <PokemonProvider>
          {children}
        </PokemonProvider>
        <img src="/images/wallpaper-prair-pokemon.jpeg" alt="Pokedesk" className={Styles.wallpaper} />
      </body>
    </html>

  );
}
