

import type { Metadata } from "next";
import "./globals.css";
import { PokemonProvider } from "./context/pokemonContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body >
        <PokemonProvider>
          {children}
          </PokemonProvider>
      </body>

    </html>

  );
}
